#!/usr/bin/env bash
# This Bash script displays numbers from 1 to 20

n=1

while [ $n -le 20 ]
do

	case $n in
		"4")
			echo "bad luck from China"
			;;
		
			"9")
			echo "bad luck from Japan"
			;;
		
			"17")
			echo "bad luck from Italya"
			;;
		*)
			echo "$n"
			;;
	esac
	n=$(( n + 1 ))
done
